# Generated by Django 5.1.6 on 2025-02-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0004_question_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='file',
            new_name='quiz_file',
        ),
    ]
